### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by sajacaros** [sajacaros/gh-flow-practice#2]
## Tasks
- [x] Print fizz, if it is mulple of 3.
- [x] Print buzz, if it is mulple of 5.
- [x] Print fizzbuzz, if it is mulple of 15.
- [x] Otherwise, print num itself.
